# Generated by Django 3.1.2 on 2020-10-09 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=32)),
                ('short_name', models.CharField(max_length=64)),
                ('long_name', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(choices=[('Y', 'Yahoo!'), ('Q', 'Quandl')], default='Y', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open_price', models.IntegerField()),
                ('close_price', models.IntegerField()),
                ('high_price', models.IntegerField()),
                ('low_price', models.IntegerField()),
                ('adjusted_close', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='symbols.symbol')),
            ],
        ),
    ]
