# Generated by Django 3.1.2 on 2020-10-15 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0002_auto_20201014_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='adjusted_close',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='price',
            name='close_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='price',
            name='high_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='price',
            name='low_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='price',
            name='open_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='price',
            name='volume',
            field=models.BigIntegerField(),
        ),
    ]
