# Generated by Django 3.1.2 on 2020-10-16 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('benchmarks', '0001_initial'),
        ('symbols', '0003_auto_20201015_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ModelPortfolioHolding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0.0)),
                ('benchmark', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portfolio_holdings', to='benchmarks.benchmark')),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portfolio_holdings', to='symbols.symbol')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='portfolios.modelportfolio')),
            ],
        ),
    ]
