# Generated by Django 3.1.2 on 2020-10-16 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_modelportfoliobench'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelportfoliobench',
            old_name='portfolio',
            new_name='benchmark',
        ),
    ]
