# Generated by Django 3.1.2 on 2020-10-16 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benchmarks', '0001_initial'),
        ('portfolios', '0003_auto_20201016_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelportfoliobench',
            name='portfolio_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='benchmarks', to='portfolios.modelportfolio'),
        ),
        migrations.AlterField(
            model_name='modelportfoliobench',
            name='benchmark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='benchmarks', to='benchmarks.benchmark'),
        ),
    ]
