# Generated by Django 3.1.2 on 2020-10-22 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_auto_20201016_0205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelportfolioholding',
            old_name='benchmark',
            new_name='benchmark_old',
        ),
    ]
