# Generated by Django 3.1.2 on 2020-10-22 19:43

from django.db import migrations

def create_benchmarks(apps, schema_editor):
    ModelPortfolioHolding = apps.get_model('portfolios', 'ModelPortfolioHolding')
    ModelPortfolioBench = apps.get_model('portfolios', 'ModelPortfolioBench')

    for holding in ModelPortfolioHolding.objects.all():
        new_bench = ModelPortfolioBench.objects.get(
            benchmark=holding.benchmark_old, portfolio=holding.portfolio
        )
        holding.bench=new_bench
        holding.save()

def create_old_benchmarks(apps, schema_editor):
    ModelPortfolioHolding = apps.get_model('portfolios', 'ModelPortfolioHolding')

    for holding in ModelPortfolioHolding.objects.all():
        old_bench = holding.bench.benchmark
        holding.benchmark_old=old_bench
        holding.save()


class Migration(migrations.Migration):
    dependencies = [
        ('portfolios', '0007_modelportfolioholding_benchmark'),
    ]

    operations = [
        migrations.RunPython(create_benchmarks, create_old_benchmarks)
    ]
