# Generated by Django 3.1.2 on 2020-10-22 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0008_auto_20201022_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelportfolioholding',
            name='bench',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='port_holdings', to='portfolios.modelportfoliobench'),
        ),
    ]
