# Generated by Django 3.1.2 on 2020-10-22 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0010_remove_modelportfolioholding_benchmark_old'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelportfolioholding',
            old_name='bench',
            new_name='benchmark',
        ),
    ]
