site_name: pmtoolsapi
site_description: An api for the portfolio management tools project
repo_url: https://github.com/FiniteSingularity/pm-tools
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/FiniteSingularity">FiniteSingularity</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
